#服务端口
server:
  port: 7082
# 应用名称
spring:
  application:
    name: id-generator
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/tes?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      # 最大连接池数量
#      maxActive: 60
#      # 获取连接时最大等待时间，单位毫秒
#      maxWait: 60000
#      # 配置一个连接在池中最小生存的时间,单位是毫秒
#      #      min-evictable-idle-time-millis: 3000
#      # 指定当连接超过废弃超时时间时，是否立刻删除该连接
#      removeAbandoned: true
#      # 指定连接应该被废弃的时间
#      removeAbandonedTimeout: 60
#      # 使用DBCP connection pool，是否追踪废弃statement或连接，默认为: false
#      logAbandoned: true
  redis:
    database: 5
    host: 192.168.2.102
    port: 6379
    password: 7ygvUJM
    timeout: 3000
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
