#服务端口
server:
  port: 6660
# 应用名称
spring:
  application:
    name: example-sing-service
  redis:
    host: www.cookframe.com
    port: 6379
    password: qaz123
    database: 0
api-stat:
  pointcut: execution(* com.example..*.*(..))
  enable: true