#服务端口
server:
  port: 6666
# 应用名称
spring:
  application:
    name: service-case
  redis:
    host: www.cookframe.com
    port: 6379
    password: qaz123
    database: 0

logging:
  level:
    example:
      mapper : debug
    tracer: trace
redisson:
  timeout: 3000
  address: www.cookframe.com
  port: 6379
  password: qaz123
  database: 5
  connectionPoolSize: 64
  connectionMinimumIdleSize: 10
         
api:
  enable: true
  platformTypes:
    - DingDing
  platformAddress:
    dingDingWebhook: https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxx