#服务端口
server:
  port: 7081
# 应用名称
spring:
  application:
    name: course-case
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/tes?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 最大连接池数量
      maxActive: 200
      # 获取连接时最大等待时间，单位毫秒
      maxWait: 60000
      # 配置一个连接在池中最小生存的时间,单位是毫秒
      #      min-evictable-idle-time-millis: 3000
      # 指定当连接超过废弃超时时间时，是否立刻删除该连接
      removeAbandoned: true
      # 指定连接应该被废弃的时间
      removeAbandonedTimeout: 60
      # 使用DBCP connection pool，是否追踪废弃statement或连接，默认为: false
      logAbandoned: true

logging:
  level:
    example:
      mapper : debug
    tracer: trace
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
redisson:
  timeout: 3000
  address: 192.168.2.102
  port: 6379
  password: 7ygvUJM
  database: 5
  connectionPoolSize: 64
  connectionMinimumIdleSize: 10    