server:
  port: 6068
spring:
  application:
    name: gateway-api
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 5
    host: 192.168.2.102
    port: 6379
    password: 7ygvUJM
    timeout: 3000  
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8768
        dashboard: localhost:8082    
    gateway:
      enabled: true
      discovery:
        locator:
          # 开启负载均衡对网关的路由转发的支持
          enabled: true
       # 如果使用全局熔断，则自定义熔断中单独接口超时时间如果大于全局超时时间则失效，因为两个熔断器都会执行   
#      default-filters:
#        # 熔断过滤器
#        - name: Hystrix
#          args:
#            name: fallBackHandler
#            id: Hystrix
#            fallbackuri: forward:/fallBackHandler    
      # 负载均衡路由规则 开启路由后的服务swagger才能显示
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/gateway/product/**
          filters:
            - StripPrefix=2
          #            - RewritePath=/gateway/log(?<segment>/?.*), $\{segment}
          metadata:
            title: 产品系统

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/gateway/order/**
          filters:
            - StripPrefix=2
          #            - RewritePath=/gateway/log(?<segment>/?.*), $\{segment}
          metadata:
            title: 订单系统
            
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/gateway/employee/**
          filters:
            - StripPrefix=2
          #            - RewritePath=/gateway/log(?<segment>/?.*), $\{segment}
          metadata:
            title: 职员系统    
            
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/gateway/department/**
          filters:
            - StripPrefix=2
          #            - RewritePath=/gateway/log(?<segment>/?.*), $\{segment}
            # 降级配置
            - name: SpecialHystrix
              args:
                id: fallBackHandler
                fallbackUri: forward:/fallBackHandler
                timeout:
                  #接口超时处理 以-代替/
                  department-get: 6000
          metadata:
            title: 部门系统      

feign:
#  sentinel:
#    enabled: false
  hystrix:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true

#hystrix: 顶层配置，表示这是Hystrix的配置。
hystrix:
  #command: 表示要配置的是Hystrix命令（即要应用断路器的方法）。
  command:
    default:
      #execution: 表示与命令执行相关的配置。
      execution:
        timeout:
          enabled: true
        #isolation: 表示与命令隔离相关的配置。
        isolation:
          #thread: 表示使用线程隔离策略。
          thread:
            #timeoutInMilliseconds: 设置超时时间，单位为毫秒。
            timeoutInMilliseconds: 3000
    #将熔断的隔离模式显示为thread模式，否则服务调用为信号量模式
    fallBackHandler:
      execution:
        isolation:
          strategy: THREAD
  threadpool:
    default:
      # Hystrix 更改默认并发数配置
      coreSize: 50        
# gateway调用服务此ribbon配置参数失效，使用feign调用服务时生效，超时时间为ribbon.ReadTimeout + ribbon.ConnectTimeout
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
  security:
    enabled: false
