# 应用名称
spring:
  application:
    name: distribute-cache
  redis:
    database: #Redis数据库索引（默认为0）
    host: #Redis服务器地址
    port: #Redis服务器连接端口
    password: #Redis服务器连接密码（默认为空）
    timeout: #连接超时时间（毫秒）
    pool:
      max-active: #连接池最大连接数（使用负值表示没有限制）
      max-wait: #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: #连接池中的最大空闲连接 
      min-idle: #连接池中的最小空闲连接


