#服务端口
server:
  port: 6068
# 应用名称
spring:
  application:
    name: gateway
  # nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        # 标识
        metadata:
          mark: true
    gateway:
      discovery:
        locator:
          # 开启负载均衡对网关的路由转发的支持
          enabled: true
      default-filters:
        # 熔断过滤器
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackuri: forward:/fallbackhandler
      # 负载均衡路由规则 开启路由后的服务swagger才能显示
      routes:
        - id: product-provider-service
          uri: lb://product-provider-service
          predicates:
            - Path=/gateway/product/**
          filters:
            - StripPrefix=2
          #            - RewritePath=/gateway/log(?<segment>/?.*), $\{segment}
          metadata:
            title: 产品系统

        - id: order-consumer-service
          uri: lb://order-consumer-service
          predicates:
            - Path=/gateway/order/**
          filters:
            - StripPrefix=2
          #            - RewritePath=/gateway/log(?<segment>/?.*), $\{segment}
          metadata:
            title: 订单系统
      
      enabled: true      
  main:
    allow-bean-definition-overriding: true
feign:
  hystrix:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      #配置请求 GZIP 压缩
      enabled: true
      #配置压缩支持的 MIME TYPE
      mime-types: text/xml,application/xml,application/json
      #配置压缩数据大小的最小阀值，默认 2048
      min-request-size: 512
    response:
      #配置响应 GZIP 压缩
      enabled: true

#hystrix: 顶层配置，表示这是Hystrix的配置。
hystrix:
  #command: 表示要配置的是Hystrix命令（即要应用断路器的方法）。
  command:
    default:
      coreSize: 50
      #execution: 表示与命令执行相关的配置。
      execution:
        timeout:
          enabled: true
        #isolation: 表示与命令隔离相关的配置。
        isolation:
          #thread: 表示使用线程隔离策略。
          thread:
            #timeoutInMilliseconds: 设置超时时间，单位为毫秒。
            timeoutInMilliseconds: 10000
            ribbon:
              ReadTimeout: 60000
              ConnectTimeout: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
  security:
    enabled: false