#服务端口
server:
  port: 9082
# 应用名称
spring:
  application:
    name: department-provider-service
  # nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        # 标识
        metadata:
          mark: true
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8082
#      datasource:
#        degrade:
#          apollo:
#            flowRulesKey: ${spring.application.name}-${spring.cloud.sentinel.datasource.degrade.apollo.rule-ruleType}-rules
#            namespace-name: ${sentinel.datasource.rules.apollo.namespace-name}
#            ruleType: degrade
#        flow:
#          apollo:
#            flowRulesKey: ${spring.application.name}-${spring.cloud.sentinel.datasource.flow.apollo.ruleType}-rules
#            namespace-name: ${sentinel.datasource.rules.apollo.namespace-name}
#            ruleType: flow
      eager: true
  main:
    allow-bean-definition-overriding: true
feign:
  sentinel:
    enabled: true
  hystrix:
    enabled: false
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      #配置请求 GZIP 压缩
      enabled: true
      #配置压缩支持的 MIME TYPE
      mime-types: text/xml,application/xml,application/json
      #配置压缩数据大小的最小阀值，默认 2048
      min-request-size: 512
    response:
      #配置响应 GZIP 压缩
      enabled: true

#hystrix: 顶层配置，表示这是Hystrix的配置。
hystrix:
  #command: 表示要配置的是Hystrix命令（即要应用断路器的方法）。
  command:
    default:
      coreSize: 50
      #execution: 表示与命令执行相关的配置。
      execution:
        timeout:
          enabled: true
        #isolation: 表示与命令隔离相关的配置。
        isolation:
          #thread: 表示使用线程隔离策略。
          thread:
            #timeoutInMilliseconds: 设置超时时间，单位为毫秒。
            timeoutInMilliseconds: 10000
            ribbon:
              ReadTimeout: 60000
              ConnectTimeout: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
  security:
    enabled: false








#app:
#  id: msa-log
#apollo:
#  meta: http://192.168.2.65:8080
#  bootstrap:
#    enabled: true
#    namespaces:  100001.common-config-h,application
#    eagerLoad:
#      enabled: true
#sentinel:
#  datasource:
#    rules:
#      apollo:
#        namespace-name: 100001.nacos-notify
